@startuml
Title Admin Startpage
state customers.jsp
state orderline.jsp
state adminstart.jsp
state start.jsp

note top of customers.jsp
Shows all customers
in the database.
Has search function.
end note

note top of orderline.jsp
Shows all orders
in the database.
Has search and
delete function.
end note

note right of start.jsp
Takes admin
to the customer
start page.
end note

[*] --> adminstart.jsp
adminstart.jsp --> customers.jsp
adminstart.jsp --> orderline.jsp
adminstart.jsp --> start.jsp
customers.jsp --> [*]
orderline.jsp --> [*]
start.jsp --> [*]

@enduml