@startuml
title Checkout
state checkout.jsp
state returnButton
state start.jsp

note left of checkout.jsp
Customer can see a
list of their purchased
cupcakes. Order is added
to the database.
end note

[*] --> checkout.jsp
checkout.jsp --> returnButton : return to start page
returnButton --> start.jsp
start.jsp --> [*]

@enduml