@startuml
title Purchase Sequence Diagram
actor Customer
boundary start.jsp
boundary cart.jsp
boundary checkout.jsp
control FrontController
participant Redirect
participant Command
participant Checkout
participant LogicFacade
Participant OrderMapper
Participant CustomerMapper
Database CupCakeDatabase

Customer -> cart.jsp : klik "køb"
cart.jsp -> FrontController : doPost()
FrontController -> FrontController : processRequest()
FrontController -> Command : from()
Command --> FrontController : checkout
FrontController -> Checkout : execute()
Checkout -> LogicFacade : pay()
Checkout -> LogicFacade : addOrder()
Checkout -> LogicFacade : addOrderLine()
LogicFacade -> CustomerMapper : pay()
LogicFacade -> OrderMapper : addOrder()
LogicFacade -> OrderMapper : addOrderLine()
CustomerMapper -> CupCakeDatabase : executeUpdate()
OrderMapper -> CupCakeDatabase : executeUpdate()
OrderMapper -> CupCakeDatabase : executeUpdate()
CupCakeDatabase --> CustomerMapper : OK
CupCakeDatabase --> OrderMapper : OK
CustomerMapper --> LogicFacade : OK
OrderMapper --> LogicFacade : OK
LogicFacade --> Checkout : OK
Checkout --> Redirect : hasPaid = true
Checkout --> FrontController : return "checkout"
FrontController --> checkout.jsp : forward()
checkout.jsp --> Redirect : clear() (tilbage-knap)
Redirect --> FrontController : return "start"
FrontController --> start.jsp : forward()
@enduml