@startuml
title Purchase Sequence Diagram
actor Customer
boundary start.jsp
boundary cart.jsp
boundary checkout.jsp
control FrontController
participant Command
participant Checkout
participant Redirect
Participant OrderMapper
Participant CustomerMapper
Database CupCakeDatabase

Customer -> cart.jsp : klik "køb"
cart.jsp -> FrontController : doPost()
FrontController -> FrontController : processRequest()
FrontController -> Command : from()
Command --> FrontController : result
FrontController -> Checkout : execute()
Checkout -> OrderMapper : execute()
Checkout -> CustomerMapper : execute()
OrderMapper -> CupCakeDatabase : addOrderLine()
CustomerMapper -> CupCakeDatabase : pay()
CupCakeDatabase -> CupCakeDatabase : executeUpdate()
CupCakeDatabase --> Checkout : hasPaid = true
Checkout --> FrontController : return "checkout"
FrontController --> checkout.jsp : forward
checkout.jsp --> Redirect : click back button
Redirect --> FrontController : return "start"
FrontController --> start.jsp : forward
@enduml